"""Frozen execution and geometric-comparison tolerances."""

MIN_SOLID_VOLUME = 1e-9
BOOLEAN_VOLUME_ABSOLUTE_TOLERANCE = 1e-9
BOOLEAN_VOLUME_RELATIVE_TOLERANCE = 1e-9
PAIRED_VOLUME_ABSOLUTE_TOLERANCE = 1e-9
PAIRED_VOLUME_RELATIVE_TOLERANCE = 1e-9
PAIRED_BOUNDING_BOX_ABSOLUTE_TOLERANCE = 1e-8
PAIRED_BOUNDING_BOX_RELATIVE_TOLERANCE = 1e-9
VECTOR_NORM_TOLERANCE = 1e-12
ERROR_DETAIL_LIMIT = 240
REPORT_VERSION = 1
